# -*- coding: utf-8 -*-
"""SVCpracticle-5352

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18dIX7JM5mNhc4JE44YRcCe5QdBOkEakq
"""

from matplotlib.pyplot import*
x=(1,2,3,4,5,6)
y= (51,32,34,12,25,34)
plot(x,y, marker="o",color="red",markersize=15,linewidth=5,linestyle="dotted",markerfacecolor="blue",markeredgecolor="yellow")
show()

from matplotlib.pyplot import*
from numpy import*

x= arange(-50,50,1)
y= x**2 
plot(x,y,linewidth="1",linestyle="dotted",color="red", marker="o",markerfacecolor="blue", markeredgecolor="yellow")
show()